name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        MIX_ENV=ci mix local.rebar --force
        MIX_ENV=ci mix local.hex --force
        MIX_ENV=ci mix deps.get
    - name: Start EPMD
      run: epmd -daemon
    - name: Run All Tests
      run: |
        MIX_ENV=ci mix quality.ci
        MIX_ENV=ci mix test.cluster
