name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              otp: 24
              elixir: 1.12
          - pair:
              otp: 25
              elixir: 1.14
          - pair:
              otp: 26.0-rc2
              elixir: 1.14.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Test
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{matrix.pair.elixir}}
          otp-version: ${{matrix.pair.otp}}

      - name: Install → Compile dependencies
        run: |
          MIX_ENV=test mix do deps.get, compile

      - name: Start epmd
        run: |
          epmd -daemon

      - name: Run tests
        run: |
          MIX_ENV=test mix test
